key: "group_header_options"
title: "Header and Footer Options"
location:
  -
    - { param: "post_type", operator: "==", value: "page" }
  -
    - { param: "post_type", operator: "==", value: "post" }
  -
    - { param: "post_type", operator: "==", value: "success_stories" }
menu_order: 1
position: "side"
style: "default"
label_placement: "top"
instruction_placement: label
hide_on_screen: ""
fields:
  -
    key:  "header_options_title"
    label:  "Title"
    name:  "header_title"
    type:  "text"
    instructions:  "Will default to the page or post type if blank"
    required:  0,
    conditional_logic:  0,
    wrapper:  { width:  "", class:  "", id:  "" }
    default_value:  ""
    placeholder:  ""
    prepend:  ""
    append:  ""
    maxlength:  ""
    readonly:  0,
    disabled:  0
  -
    key:  "header_options_subtitle"
    label:  "Subtitle"
    name:  "header_subtitle"
    type:  "text"
    instructions:  ""
    required:  0,
    conditional_logic:  0,
    wrapper:  { width:  "", class:  "", id:  "" }
    default_value:  ""
    placeholder:  ""
    prepend:  ""
    append:  ""
    maxlength:  ""
    readonly:  0,
    disabled:  0
  -
    key:  "header_options_image"
    label:  "Image"
    name:  "header_image"
    type:  "image"
    instructions:  ""
    required:  0
    conditional_logic:  0
    wrapper:  {width:  "", class:  "", id:  "" }
    return_format:  "array"
    preview_size:  "thumbnail"
    library:  "all"
    min_width:  ""
    min_height:  ""
    min_size:  ""
    max_width:  ""
    max_height:  ""
    max_size:  ""
    mime_types:  ""
  -
    key:  "footer_options_form"
    label:  "Hide Contact Form"
    name:  "footer_contact_form"
    type:  "true_false"
    instructions:  ""
    required:  0,
    conditional_logic:  0,
    wrapper:  { width:  "", class:  "", id:  "" }
